### Database update

In [1]:
import time
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy.types import Float, Integer

buoy, loc = 'CLIS', 'sfc'

# Variables and valid ranges
vars = ['T', 'S', 'DO', 'P', 'C', 'pH', 'rho', 'DOsat']
ranges = {'T': (-5, 30), 'S': (5, 35), 'DO': (0, 20), 'P': (0, 50),
          'C': (0, 50),'pH': (6, 10), 'rho': (16, 25), 'DOsat': (0, 150)}

# Create database engine
engine = create_engine('postgresql+psycopg2://lisicos:vncq489@merlin.dms.uconn.edu:5432/buoyQAQC')

# Apply threshold test
def process_df(df):
    for v in vars:
        d_col, q_col, c_col = f'{v}_data', f'{v}_Q', f'{v}_FailedCount'
        q_str = df[q_col].astype(str).str.zfill(5)
        first, rest = q_str.str[0], q_str.str[1:]
        # Fail: NaN or out of range
        mask = df[d_col].isna() | (df[d_col] < ranges[v][0]) | (df[d_col] > ranges[v][1])
        first.loc[mask] = '4'
        # Update QA/QC columns
        new_q = first + rest
        df[q_col] = new_q.astype(int)
        df[c_col] = new_q.str.count('4').astype(int)
    return df

# Update database in chunks via temp table
def update_db(tbl, chunk_size=50000):
    print(f'Start updating {tbl}:')
    df = process_df(pd.read_sql(f'SELECT * FROM "{tbl}"', engine))
    total = len(df)

    # Open raw database connection and cursor
    conn = engine.raw_connection()
    cursor = conn.cursor()
    
    # Columns to update (exclude primary key)
    cols = [col for col in df.columns if col != 'TmStamp']
    set_clause = ', '.join([f'"{col}" = tmp."{col}"' for col in cols])
    
    start = time.time()

    for i in range(0, total, chunk_size):
        chunk = df.iloc[i:i+chunk_size]
        tmp = f'{tbl}_temp'
        # Define SQL column types
        dtype = {
            f'{v}_{s}': t
            for v in vars
            for s, t in [('data', Float), ('Q', Integer), ('FailedCount', Integer)]
        }
        # Write temp table
        chunk.to_sql(tmp, engine, if_exists='replace', index=False, method='multi', dtype=dtype)
        # Update target table
        cursor.execute(f'''
            UPDATE "{tbl}" AS tgt
            SET {set_clause}
            FROM "{tmp}" AS tmp
            WHERE tgt."TmStamp" = tmp."TmStamp";
            ''')
        # Drop temp table after update
        cursor.execute(f'DROP TABLE "{tmp}";')
        conn.commit()
        # Track progress
        print(f'[{tbl}] {min(i + chunk_size, total)}/{total} | {time.time()-start:.1f}s')
    
    cursor.close()
    conn.close()
    print(f'Finish updating {tbl}.\n')

# Run function
update_db(f'{buoy}_{loc}_QAQC')

Start updating CLIS_sfc_QAQC:
[CLIS_sfc_QAQC] 50000/102419 | 351.1s
[CLIS_sfc_QAQC] 100000/102419 | 610.1s
[CLIS_sfc_QAQC] 102419/102419 | 639.2s
Finish updating CLIS_sfc_QAQC.

### QA/QC results

In [1]:
import pandas as pd

flags = {'Pass': 1, 'Suspect': 3, 'Fail': 4}
results = []

for stn in ['A4', 'C1', 'E1', 'I2']:
    # Load dataset
    df = pd.read_csv(f'DEEP_{stn}_WQ_QAQC.csv')
    df['time'] = pd.to_datetime(df['time'], errors='coerce')
    df = df[df['time'] < '2025-01-01']
    
    # QA/QC results for selected CTDEEP stations
    for var in ['T', 'S', 'DO']:
        row = {'Station': stn, 'Variable': var}
        for label, flag in flags.items():
            count = (df[f'{var}_Q'] == flag).sum()
            pct = 100 * count / len(df)
            row[label] = f'{count} ({pct:.1f}%)'
        results.append(row)

qaqc_summary = pd.DataFrame(results)
qaqc_summary

   Station Variable           Pass      Suspect         Fail
0       A4        T  79503 (93.5%)  2293 (2.7%)  3248 (3.8%)
1       A4        S  78109 (91.8%)  3513 (4.1%)  3422 (4.0%)
2       A4       DO  76520 (90.0%)  3640 (4.3%)  4884 (5.7%)
3       C1        T  46410 (92.1%)   715 (1.4%)  3261 (6.5%)
4       C1        S  46574 (92.4%)   289 (0.6%)  3523 (7.0%)
5       C1       DO  45535 (90.4%)   634 (1.3%)  4217 (8.4%)
6       E1        T  84074 (93.2%)  1924 (2.1%)  4163 (4.6%)
7       E1        S  82793 (91.8%)  2789 (3.1%)  4579 (5.1%)
8       E1       DO  83702 (92.8%)   947 (1.1%)  5512 (6.1%)
9       I2        T  57884 (90.7%)  1773 (2.8%)  4140 (6.5%)
10      I2        S  57793 (90.6%)  1610 (2.5%)  4394 (6.9%)
11      I2       DO  56761 (89.0%)  1662 (2.6%)  5374 (8.4%)

In [2]:
buoy, locs = 'ARTG', ['btm1','btm2','sfc']
qaqc_tests = ['Threshold', 'JumpLim', 'Gap', 'PresRng', 'Spike']
results = []

for loc in locs:
    # Load dataset
    df = pd.read_csv(f'{buoy}_{loc}_QAQC.csv')
    df['TmStamp'] = pd.to_datetime(df['TmStamp'], format='%d-%b-%Y %H:%M:%S', errors='coerce')
    df = df[df['TmStamp'] < '2025-01-01']

    # Summary of QA/QC test failures for the selected buoy
    for var in ['T', 'S', 'DO']:
        q = df[f'{var}_Q'].astype(str).str.zfill(5)
        row = {'Location': loc, 'Variable': var}
        for i, test in enumerate(qaqc_tests):
            fail_count = (q.str[i].astype(int) == 4).sum()
            fail_pct = 100 * fail_count / len(q)
            row[test] = f'{fail_count} ({fail_pct:.1f}%)'
        results.append(row)

qaqc_summary = pd.DataFrame(results)
qaqc_summary

,Location,Variable,Threshold,JumpLim,Gap,PresRng,Spike
0,btm1,T,279 (0.1%),487 (0.2%),59 (0.0%),290 (0.1%),487 (0.2%)
1,btm1,S,279 (0.1%),487 (0.2%),59 (0.0%),290 (0.1%),487 (0.2%)
2,btm1,DO,287 (0.1%),487 (0.2%),59 (0.0%),290 (0.1%),487 (0.2%)
3,btm2,T,282 (0.1%),487 (0.3%),630 (0.3%),289 (0.1%),485 (0.2%)
4,btm2,S,283 (0.1%),476 (0.2%),630 (0.3%),289 (0.1%),475 (0.2%)
5,btm2,DO,2801 (1.4%),2986 (1.5%),630 (0.3%),289 (0.1%),2986 (1.5%)
6,sfc,T,295 (0.1%),502 (0.2%),26 (0.0%),312 (0.2%),502 (0.2%)
7,sfc,S,5811 (2.8%),502 (0.2%),26 (0.0%),312 (0.2%),502 (0.2%)
8,sfc,DO,325 (0.2%),502 (0.2%),26 (0.0%),312 (0.2%),502 (0.2%)